/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisgelar.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.MaskFormatter;
import sisgelar.controller.PessoaController;
import sisgelar.model.Pessoa;
import sisgelar.controller.Utilitarios;
import sisgelar.model.ProdutoCliente;

/**
 *
 * @author kaikealexsander
 */
public class JFCadClientes extends javax.swing.JFrame {

    private ProdutoCliente produto;

    /**
     * Creates new form JFCadClientes
     */
    public JFCadClientes() {
        initComponents();
        inicia();
        buscaInicial(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jftfCelular = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter celular = new javax.swing.text.MaskFormatter("(##)#####-####");
            celular.setPlaceholderCharacter('_');
            jftfCelular = new javax.swing.JFormattedTextField(celular);
        } catch (Exception e){ }
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbPessoa = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnCancelaCadastro = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        txtEndereco = new javax.swing.JTextField();
        txtIdPessoa = new javax.swing.JFormattedTextField();
        txtPessoa = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lblNomeFantasia = new javax.swing.JLabel();
        txtNomeFantasia = new javax.swing.JTextField();
        jftfCep = new javax.swing.JFormattedTextField();
        try{
            javax.swing.text.MaskFormatter cep = new javax.swing.text.MaskFormatter("#####-###");
            cep.setPlaceholderCharacter('_');
            jftfCep = new javax.swing.JFormattedTextField(cep);
        } catch (Exception e){ }
        jLabel8 = new javax.swing.JLabel();
        jftfCelular2 = new javax.swing.JTextField();
        try{  javax.swing.text.MaskFormatter celular2 = new javax.swing.text.MaskFormatter("(##)#####-####");
            celular2.setPlaceholderCharacter('_');
            jftfCelular2 = new javax.swing.JFormattedTextField(celular2); }
        catch (Exception e){ }
        jLabel5 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jftfTelefone = new javax.swing.JFormattedTextField();
        try{ 
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("(##)#####-####");
            telefone.setPlaceholderCharacter('_');
            jftfTelefone = new javax.swing.JFormattedTextField(telefone);
        } catch (Exception e){ }
        jLabel4 = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFbairro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jftNumero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Celular:");

        jLabel2.setText("Telefone:");

        jcbPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PF", "PJ" }));

        jLabel1.setText("Pessoa:");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        btnCancelaCadastro.setText("Cancelar");
        btnCancelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaCadastroActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Salvar");
        btnCadastrar.setEnabled(false);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        Limpar.setText("Novo");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblNomeFantasia.setText("Nome Fantasia:");

        txtNomeFantasia.setText(" ");

        jftfCep.setText(" ");

        jLabel8.setText("CEP:");

        jLabel5.setText("E-mail:");

        jLabel4.setText("Celular2:");

        lbEndereco.setText("Endereço:");

        lbNome.setText("Cliente:");

        jLabel6.setText("Bairro:");

        jTFbairro.setText(" ");

        jLabel7.setText("Nº:");

        jftNumero.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbEndereco, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbNome, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBuscar))
                                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jftfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jftfCelular2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTFbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jftNumero))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jcbPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblNomeFantasia)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelaCadastro)
                                .addGap(18, 18, 18)
                                .addComponent(btnCadastrar)))
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(txtPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(txtIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jcbPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFantasia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jftNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jftfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jftfCelular2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTFbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnCancelaCadastro)
                    .addComponent(btnAlterar)
                    .addComponent(Limpar)
                    .addComponent(btnExcluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        tabela.getSelectionModel().addListSelectionListener(tabela);
        if (tabela.getSelectedRow() >= 0) {
            Pessoa p = new Pessoa();

            //            txtIdPessoa.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            //            txtPessoa.setText(""+tabela.getValueAt(tabela.getSelectedRow(), 1));
            String cpfCnpj = tabela.getValueAt(tabela.getSelectedRow(), 2).toString();
            if(cpfCnpj.length()>14){
                jcbPessoa.setSelectedItem("PJ");
            }else
            jcbPessoa.setSelectedItem("PF");
            //                txtCPF.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
            //                txtEndereco.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
            int pC = Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            preencheCampos(pC);

            btnExcluir.setEnabled(true);
            btnAlterar.setEnabled(true);
            btnCadastrar.setEnabled(false);
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnCancelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaCadastroActionPerformed
        new Utilitarios().limparTodosCampos(rootPane);
        dispose();
    }//GEN-LAST:event_btnCancelaCadastroActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if(
            !txtPessoa.getText().equals("") ||
            !txtCPF.getText().equals("") ||
            !txtEndereco.getText().equals("")
        ){
            DefaultTableModel tabelaNova = new DefaultTableModel();
            tabelaNova.setColumnIdentifiers(new String[]{"ID", "NOME", "ENDEREÇO", "CPF/CNPJ"});

            TableModel tabelaAtual = tabela.getModel();

            for(int i=0; i<tabelaAtual.getRowCount(); i++){
                tabelaNova.addRow(
                    new String[]{
                        tabelaAtual.getValueAt(i,0).toString(), //id
                        tabelaAtual.getValueAt(i,1).toString(), //produto
                        tabelaAtual.getValueAt(i,2).toString(), //desc
                        tabelaAtual.getValueAt(i,3).toString(), //valor
                    });
                }
                recebeCampos();
                
                Object[] linha = {null, txtPessoa.getText(), txtCPF.getValue(), txtEndereco.getText()};
                //cadastrando um produto
 //(int idpessoa, String nome, String cpf, String endereco, String cep, String bairro, String email, String telefone, String celular, String celular2) 
                Pessoa p3 = new Pessoa(0, pessoa, cpf, endereco, cep, bairro, email, telefone, celular, celular2, fantasia, numero);
                //  Pessoa p = new Pessoa(0, txtPessoa.getText(), txtCPF.getText(), txtEndereco.getText());
                boolean cadastrado = PessoaController.cadastrar(p3);
                if (cadastrado){
                    JOptionPane.showMessageDialog(null, txtPessoa.getText()+" Cadastrado com sucesso!");
                    tabelaNova.addRow(linha);
                    tabela.setModel(tabelaNova);
                    //limpa o formulario
                    buscaInicial("");
                    btnCadastrar.setEnabled(false);
                }
                else
                JOptionPane.showMessageDialog(null, "Erro!");
            }
            else
            JOptionPane.showMessageDialog(null, "Preencha as informações!");
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String b = txtPessoa.getText();
        buscaInicial(b);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        new Utilitarios().limparTodosCampos(rootPane);
        btnCadastrar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_LimparActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        //query = "update tbProdutos set produto=?, descricao=?, valor=? where idProduto=?";
        switch (JOptionPane.showConfirmDialog(null, "Deseja realmente alterar as informações?","Atenção", JOptionPane.YES_NO_OPTION )) {
            case 0:
            //System.out.println("botao yes clicado");
            recebeCampos();
            
            Pessoa p3 = new Pessoa(codigo, pessoa, cpf, endereco, cep, bairro, email, telefone, celular, celular2, fantasia, numero);
            PessoaController.modificar(p3);
                System.out.println(codigo);
            buscaInicial("");
            break;
            case 1:
            break;
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        switch (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o produto?","Atenção", JOptionPane.YES_NO_OPTION )) {
            case 0:
            //System.out.println("botao yes clicado");
            recebeCampos();
            Pessoa p3 = new Pessoa(codigo, pessoa, cpf, endereco, cep, bairro, email, telefone, celular, celular2, fantasia, numero);
            PessoaController.remover(p3);
            buscaInicial("");
            break;
            case 1:
            break;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCadClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCadClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelaCadastro;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFbairro;
    private javax.swing.JComboBox<String> jcbPessoa;
    private javax.swing.JTextField jftNumero;
    private javax.swing.JTextField jftfCelular;
    private javax.swing.JTextField jftfCelular2;
    private javax.swing.JFormattedTextField jftfCep;
    private javax.swing.JFormattedTextField jftfTelefone;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lblNomeFantasia;
    private javax.swing.JTable tabela;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JFormattedTextField txtIdPessoa;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtPessoa;
    // End of variables declaration//GEN-END:variables

    private String b="";
    
    int codigo;
    String pessoa;
    String endereco;
    String cpf;
    String telefone;
    String celular;
    String celular2;
    String cep;
    String bairro;
    String email;
    String fantasia;
    String numero;
    
        public void recebeCampos(){
            if (txtIdPessoa.getText().length()>0){
                codigo   =  Integer.parseInt(txtIdPessoa.getText());
            }else codigo = 0;
        pessoa   =  txtPessoa.getText();
        endereco =  txtEndereco.getText();
        cpf      =  txtCPF.getText();
        telefone =  jftfTelefone.getText();
        celular  =  jftfCelular.getText();
        celular2 =  jftfCelular2.getText();
        cep      =  jftfCep.getText();
        email    =  jtfEmail.getText();
        bairro   =  jTFbairro.getText();
        numero   =  jftNumero.getText();
    }
    
    public void preencheCampos(int pC){
       // List<Pessoa> pessoas = PessoaController.pesquisar(codigo);
        for (Pessoa ps : PessoaController.pesquisar(pC)){
            txtIdPessoa.setText(""+ps.getIdpessoa());
            txtPessoa.setText(ps.getNome());
            txtEndereco.setText(ps.getEndereco());
            txtCPF.setText(ps.getCpf());
            jftfTelefone.setText(ps.getTelefone());
            jftfCelular.setText(ps.getCelular());
            jftfCelular2.setText(ps.getCelular2());
            jftfCep.setText(ps.getCep());
            jtfEmail.setText(ps.getEmail());
            jTFbairro.setText(ps.getBairro());
            jftNumero.setText(ps.getNumero());
            
        }
    }
       
    private void buscaInicial(String b){        
        
           DefaultTableModel busctab = new DefaultTableModel();
           String[] nomesColunas = new String[]{"ID","NOME", "CPF/CNPJ", "ENDEREÇO"};
           busctab.setColumnIdentifiers(nomesColunas);
           busctab.setNumRows(0);

            for (Pessoa p : PessoaController.pesquisar(b)) {
                            busctab.addRow(new Object[]{
                                p.getIdpessoa(),
                                p.getNome(),
                                p.getCpf(),
                                p.getEndereco()});
            }
            tabela.setModel(busctab);
            tabela.getColumnModel().getColumn(0).setPreferredWidth(5);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabela.getColumnModel().getColumn(2).setPreferredWidth(100);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(150);
            new Utilitarios().limparTodosCampos(rootPane);
    }             

     private MaskFormatter Mascara(String Mascara) {

        try {
            MaskFormatter stringMascara = new MaskFormatter(Mascara);
            //   stringMascara.setMask(Mascara);
            stringMascara.setPlaceholderCharacter(' ');
        } catch (Exception e) {            
            e.printStackTrace();
        }
            MaskFormatter stringMascara = null;
        return stringMascara;
     }

        public void inicia(){
        jcbPessoa.addActionListener(new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent event) {
            JComboBox<String> combo = (JComboBox<String>) event.getSource();
            String selectedBook = (String) combo.getSelectedItem();

            if (selectedBook.equals("PF")) {
                try {
                    System.out.println("Pessoa Fisica!");
                    txtCPF.setFormatterFactory(null);
                    javax.swing.text.MaskFormatter format = new javax.swing.text.MaskFormatter("###.###.###-##");
                    format.setPlaceholderCharacter('_');
                    txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(format));
                    txtCPF.setValue(null);
                    lblNomeFantasia.setEnabled(false);
                    txtNomeFantasia.setEnabled(false);
                } catch (ParseException ex) {
                    Logger.getLogger(JFCadClientes.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else if (selectedBook.equals("PJ")) {
                try {
                    txtCPF.setFormatterFactory(null);
                    javax.swing.text.MaskFormatter format = new javax.swing.text.MaskFormatter("##.###.###/####-##");
                    format.setPlaceholderCharacter('_');
                    txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(format));
                    txtCPF.setValue(null);
                    lblNomeFantasia.setEnabled(true);
                    txtNomeFantasia.setEnabled(true);
                } catch (ParseException ex) {
                    Logger.getLogger(JFCadClientes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    });
    }

    void setProduto(ProdutoCliente prod) {
        this.produto = prod;
    }
  
}




