/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisgelar.view;


import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import sisgelar.view.internal.JIFAgenda;
import sisgelar.view.internal.JIFCadClientes;
import sisgelar.view.internal.JIFEstoque;

/**
 *
 * @author kaikealexsander
 */
public class JFPrincpal extends javax.swing.JFrame {

    /**
     * Creates new form JFPrincpal
     */
    public JFPrincpal() {
        initComponents();
        this.setLocationRelativeTo(null);//faz o janela carregar no meio da tela
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        comandoInternal(new JIFAgenda(jdpPrincipal));
    }
    
    
    public void comandoInternal(JInternalFrame frame){
        for (JInternalFrame internal : jdpPrincipal.getAllFrames()){
            if (internal.getClass().toString().equalsIgnoreCase(frame.getClass().toString())){
                //JOptionPane.showMessageDialog(rootPane, "A Janela "+frame.getTitle()+" já está aberta!");
                //InternalFrameToFront();
                internal.toFront();
                try {
                    internal.setSelected(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(JFPrincpal.class.getName()).log(Level.SEVERE, null, ex);
                }
                return;
            }
            
        }
        jdpPrincipal.add(frame);
        frame.setClosable(true);//habilita botão fechar
        frame.setIconifiable(true);//habilita botão minimizar
        frame.setMaximizable(true);//habilita botão maximizar/restaurar
        Dimension d = frame.getDesktopPane().getSize();
        frame.setLocation((d.width - frame.getSize().width) / 2, (d.height - frame.getSize().height) / 2);
        frame.setVisible(true);//exibe o frame

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        jmiSair = new javax.swing.JMenuItem();
        jmEditar = new javax.swing.JMenu();
        jmiClientes = new javax.swing.JMenu();
        jMiClientes = new javax.swing.JMenuItem();
        jmOrdensServico = new javax.swing.JMenu();
        jmiAgenda = new javax.swing.JMenuItem();
        jmiOS = new javax.swing.JMenuItem();
        jmiOSRelatorios = new javax.swing.JMenuItem();
        jmiProdutos = new javax.swing.JMenu();
        jmiEstoque = new javax.swing.JMenuItem();
        jmiEstoqueRelatorios = new javax.swing.JMenuItem();
        jmAjuda = new javax.swing.JMenu();
        jmiSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );

        jmArquivo.setText("Arquivo");

        jmiSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmArquivo.add(jmiSair);

        jMenuBar1.add(jmArquivo);

        jmEditar.setText("Editar");
        jMenuBar1.add(jmEditar);

        jmiClientes.setText("Cadastros");

        jMiClientes.setText("Clientes");
        jMiClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiClientesActionPerformed(evt);
            }
        });
        jmiClientes.add(jMiClientes);

        jMenuBar1.add(jmiClientes);

        jmOrdensServico.setText("Ordens de serviço");

        jmiAgenda.setText("Agenda");
        jmOrdensServico.add(jmiAgenda);

        jmiOS.setText("O.S");
        jmOrdensServico.add(jmiOS);

        jmiOSRelatorios.setText("Relatórios");
        jmOrdensServico.add(jmiOSRelatorios);

        jMenuBar1.add(jmOrdensServico);

        jmiProdutos.setText("Estoque");

        jmiEstoque.setText("Produtos");
        jmiEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEstoqueActionPerformed(evt);
            }
        });
        jmiProdutos.add(jmiEstoque);

        jmiEstoqueRelatorios.setText("Relatórios");
        jmiProdutos.add(jmiEstoqueRelatorios);

        jMenuBar1.add(jmiProdutos);

        jmAjuda.setText("Ajuda");

        jmiSobre.setText("Sobre");
        jmAjuda.add(jmiSobre);

        jMenuBar1.add(jmAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMiClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiClientesActionPerformed
        // TODO add your handling code here:
        comandoInternal(new JIFCadClientes(jdpPrincipal));
    }//GEN-LAST:event_jMiClientesActionPerformed

    private void jmiEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEstoqueActionPerformed
    comandoInternal(new JIFEstoque());
                // TODO add your handling code here:

    }//GEN-LAST:event_jmiEstoqueActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        switch (JOptionPane.showConfirmDialog(null, "Deseja realmente sair do Sistema?","Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE )) {
                    case 0:/*Botão 'Sim' clicado*/
                        System.exit(0);
                        break;
                    case 1:
                        break;
                }
    }//GEN-LAST:event_jmiSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMiClientes;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenu jmAjuda;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenu jmEditar;
    private javax.swing.JMenu jmOrdensServico;
    private javax.swing.JMenuItem jmiAgenda;
    private javax.swing.JMenu jmiClientes;
    private javax.swing.JMenuItem jmiEstoque;
    private javax.swing.JMenuItem jmiEstoqueRelatorios;
    private javax.swing.JMenuItem jmiOS;
    private javax.swing.JMenuItem jmiOSRelatorios;
    private javax.swing.JMenu jmiProdutos;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiSobre;
    // End of variables declaration//GEN-END:variables

    
}
