/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisgelar.view.internal;

import java.awt.Dimension;
import javax.swing.table.DefaultTableModel;
import sisgelar.controller.Utilitarios;

/**
 *
 * @author kaike
 */
public class JIFAgenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFAgenda
     */
    public JIFAgenda() {
        initComponents();
        
    }

    public void setPosicao() {//forçar iniciar no meio do desktop
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtAgenda = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jtAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Data/Hora", "Cliente", "Técnico"
            }
        ));
        jScrollPane1.setViewportView(jtAgenda);

        jLabel1.setText("Planejamento de manutenções para a semana");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtAgenda;
    // End of variables declaration//GEN-END:variables


     private void buscaInicial(String b){        
       
       DefaultTableModel busctab = new DefaultTableModel();
       String[] nomesColunas = new String[]{"ID","CLIENTE", "TECNICO", "LOCAL", "DATA/HORA"};
       busctab.setColumnIdentifiers(nomesColunas);
       busctab.setNumRows(0);
       
//       produtos = ProdutoClienteController.pesquisar(b);
//       
//        for (ProdutoCliente p : produtos) {
//			busctab.addRow(new Object[]{
//                            p.getIdProdCliente(),
//                            p.getIdCliente(),
//                            p.getMarca(),
//                            p.getLocalizacao(),
//                            p.getModelo(),
//                            p.getVoltagem()});
//        }
        
        jtAgenda.setModel(busctab);
        jtAgenda.getColumnModel().getColumn(0).setPreferredWidth(30);
        jtAgenda.getColumnModel().getColumn(1).setPreferredWidth(200);
        jtAgenda.getColumnModel().getColumn(2).setPreferredWidth(250);
        jtAgenda.getColumnModel().getColumn(3).setPreferredWidth(50);
        
        new Utilitarios().limparTodosCampos(rootPane);
        }         
    
}
