/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisgelar.view.internal;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import sisgelar.MyTableModel;
import sisgelar.controller.PessoaController;
import sisgelar.controller.ProdutoClienteController;
import sisgelar.model.Pessoa;
import sisgelar.controller.Utilitarios;
import sisgelar.model.ProdutoCliente;

/**
 *
 * @author kaike
 */
public class JIFCadClientes extends javax.swing.JInternalFrame {
        private ProdutoCliente produto;
        private JDesktopPane jdesk;


    /**
     * Creates new form JIFCadClientes
     */
    public JIFCadClientes() {
       
    }
    public JIFCadClientes(JDesktopPane jdesk){
        this.jdesk = jdesk;
        initComponents();
         inicia();
        buscaInicial(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnCancelaCadastro = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jtpProdutos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jftfTelefone = new javax.swing.JFormattedTextField();
        try{ 
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("(##)#####-####");
            telefone.setPlaceholderCharacter('_');
            jftfTelefone = new javax.swing.JFormattedTextField(telefone);
        } catch (Exception e){ }
        jcbPessoa = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        lbNome = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFbairro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jftNumero = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtIdPessoa = new javax.swing.JFormattedTextField();
        txtPessoa = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblNomeFantasia = new javax.swing.JLabel();
        txtNomeFantasia = new javax.swing.JTextField();
        jftfCep = new javax.swing.JFormattedTextField();
        try{
            javax.swing.text.MaskFormatter cep = new javax.swing.text.MaskFormatter("#####-###");
            cep.setPlaceholderCharacter('_');
            jftfCep = new javax.swing.JFormattedTextField(cep);
        } catch (Exception e){ }
        jLabel8 = new javax.swing.JLabel();
        jftfCelular2 = new javax.swing.JTextField();
        try{  javax.swing.text.MaskFormatter celular2 = new javax.swing.text.MaskFormatter("(##)#####-####");
            celular2.setPlaceholderCharacter('_');
            jftfCelular2 = new javax.swing.JFormattedTextField(celular2); }
        catch (Exception e){ }
        jftfCelular = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter celular = new javax.swing.text.MaskFormatter("(##)#####-####");
            celular.setPlaceholderCharacter('_');
            jftfCelular = new javax.swing.JFormattedTextField(celular);
        } catch (Exception e){ }
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtProdCli = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jtfCodProdCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfCodCliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfMarcaProdCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfPotenciaProdCliente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtfVoltagemProdCliente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtfModeloProdCliente = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtfLocalProdCliente = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jbtnSalvarProd = new javax.swing.JButton();
        Apagar = new javax.swing.JButton();
        jbListarProdCliente = new javax.swing.JButton();
        jlNomeCliente = new javax.swing.JLabel();
        jbAbrirOS = new javax.swing.JButton();

        setTitle("Cadastro de Clientes");

        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        btnCancelaCadastro.setText("Cancelar");
        btnCancelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaCadastroActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Salvar");
        btnCadastrar.setEnabled(false);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        Limpar.setText("Novo");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jtpProdutos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Celular:");

        jLabel2.setText("Telefone:");

        jcbPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "PF", "PJ" }));

        jLabel1.setText("Pessoa:");

        jLabel4.setText("Celular2:");

        lbEndereco.setText("Endereço:");

        lbNome.setText("Cliente:");

        jLabel6.setText("Bairro:");

        jTFbairro.setText(" ");

        jLabel7.setText("Nº:");

        jftNumero.setText(" ");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblNomeFantasia.setText("Nome Fantasia:");

        txtNomeFantasia.setText(" ");

        jftfCep.setText(" ");

        jLabel8.setText("CEP:");

        jLabel5.setText("E-mail:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbEndereco, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNome, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar))
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jftfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftfCelular2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTFbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jftNumero))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jcbPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblNomeFantasia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(txtPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(txtIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jcbPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFantasia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jftNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jftfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jftfCelular2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTFbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jtpProdutos.addTab("Dados Pessoais", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtProdCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Marca", "Modelo", "Potência", "Voltagem", "Local de Inst."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtProdCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProdCliMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtProdCli);

        jLabel10.setText("Cod:");

        jtfCodProdCliente.setText(" ");
        jtfCodProdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodProdClienteActionPerformed(evt);
            }
        });

        jLabel11.setText("Cod Cliente:");

        jtfCodCliente.setEditable(false);
        jtfCodCliente.setText("        ");
        jtfCodCliente.setEnabled(false);
        jtfCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodClienteActionPerformed(evt);
            }
        });

        jLabel12.setText("Marca:");

        jtfMarcaProdCliente.setText("                            ");
        jtfMarcaProdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMarcaProdClienteActionPerformed(evt);
            }
        });

        jLabel13.setText("Potência:");

        jtfPotenciaProdCliente.setText("     ");

        jLabel14.setText("Voltagem:");

        jtfVoltagemProdCliente.setText("    ");

        jLabel15.setText("Modelo:");

        jtfModeloProdCliente.setText("          ");
        jtfModeloProdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfModeloProdClienteActionPerformed(evt);
            }
        });

        jLabel16.setText("Local de Instalação:");

        jtfLocalProdCliente.setText("      ");

        jButton1.setText("Novo");

        jbtnSalvarProd.setText("Salvar");
        jbtnSalvarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalvarProdActionPerformed(evt);
            }
        });

        Apagar.setText("Apagar");

        jbListarProdCliente.setText("Listar");
        jbListarProdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListarProdClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbListarProdCliente)
                    .addComponent(jbtnSalvarProd)
                    .addComponent(Apagar)
                    .addComponent(jButton1))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Apagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSalvarProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbListarProdCliente)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jlNomeCliente.setText("                     ");

        jbAbrirOS.setText("Abrir O.S");
        jbAbrirOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAbrirOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtfCodProdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfCodCliente))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtfMarcaProdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtfLocalProdCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfVoltagemProdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtfModeloProdCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfPotenciaProdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAbrirOS)
                        .addGap(89, 89, 89)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jtfCodProdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jtfCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNomeCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jtfModeloProdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jtfMarcaProdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jtfPotenciaProdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jtfLocalProdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jtfVoltagemProdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAbrirOS)
                        .addGap(29, 29, 29)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jtpProdutos.addTab("Produtos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jtpProdutos, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addGap(18, 18, 18)
                .addComponent(btnCancelaCadastro)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtpProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnCancelaCadastro)
                    .addComponent(Limpar)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        tabela.getSelectionModel().addListSelectionListener(tabela);
        if (tabela.getSelectedRow() >= 0) {
            Pessoa p = new Pessoa();

            //            txtIdPessoa.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            //            txtPessoa.setText(""+tabela.getValueAt(tabela.getSelectedRow(), 1));
            String cpfCnpj = tabela.getValueAt(tabela.getSelectedRow(), 2).toString();
            if(cpfCnpj.length()>14){
                jcbPessoa.setSelectedItem("PJ");
            }else
            jcbPessoa.setSelectedItem("PF");
            //                txtCPF.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
            //                txtEndereco.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
            int pC = Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            preencheCampos(pC);

            btnExcluir.setEnabled(true);
            btnCadastrar.setEnabled(true);
            //btnCadastrar.setEnabled(false);
        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnCancelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaCadastroActionPerformed
        new Utilitarios().limparTodosCampos(rootPane);
        dispose();
    }//GEN-LAST:event_btnCancelaCadastroActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if( !txtPessoa.getText().equals("") ||/* se os campos não estiverem vazios*/
            !txtCPF.getText().equals("") ||
            !txtEndereco.getText().equals(""))
        {
            recebeCamposPessoa();
            Pessoa p3 = new Pessoa(codigo, pessoa, cpf, endereco, cep, bairro, email, telefone, celular, celular2, fantasia, numero);
            if(codigo>0)/*Se o codigo ja existir altera*/
            {
                switch (JOptionPane.showConfirmDialog(null, "Deseja realmente alterar as informações?","Atenção", JOptionPane.YES_NO_OPTION )) {
                    case 0:/*Botão 'Sim' clicado*/
                    PessoaController.modificar(p3);
                    break;
                    case 1:
                    break;
                }

            }    else{/*Se codigo não existir insert*/
                switch (JOptionPane.showConfirmDialog(null, "Deseja salvar as informações?","Atenção", JOptionPane.YES_NO_OPTION )) {
                    case 0:/*Botão 'Sim' clicado*/
                    PessoaController.cadastrar(p3);
                    break;
                    case 1:
                    break;
                }
            }
            buscaInicial("");
        }else/*caso campos não estejam preenchidos*/
        JOptionPane.showMessageDialog(null, "Preencha as informações!");
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        new Utilitarios().limparTodosCampos(rootPane);
        btnCadastrar.setEnabled(true);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_LimparActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        switch (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o produto?","Atenção", JOptionPane.YES_NO_OPTION )) {
            case 0:
            //System.out.println("botao yes clicado");
            recebeCamposPessoa();
            Pessoa p3 = new Pessoa(codigo, pessoa, cpf, endereco, cep, bairro, email, telefone, celular, celular2, fantasia, numero);
            PessoaController.remover(p3);
            buscaInicial("");
            break;
            case 1:
            break;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String b = txtPessoa.getText();
        buscaInicial(b);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jtProdCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProdCliMouseClicked
        jtProdCli.getSelectionModel().addListSelectionListener(jtProdCli);
        int proc = 0;
        if (jtProdCli.getSelectedRow() >= 0) {
            //            txtIdPessoa.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            //            txtPessoa.setText(""+tabela.getValueAt(tabela.getSelectedRow(), 1));
            proc = Integer.parseInt(jtProdCli.getValueAt(jtProdCli.getSelectedRow(), 0).toString());
            int cli =Integer.parseInt(jtfCodCliente.getText());
            for (ProdutoCliente produt : ProdutoClienteController.pesquisar(proc, cli)){
                jtfCodProdCliente.setText(""+produt.getIdProdCliente());
                jtfMarcaProdCliente.setText(""+produt.getMarca());
                jtfModeloProdCliente.setText(""+produt.getModelo());
                jtfVoltagemProdCliente.setText(""+produt.getVoltagem());
                jtfLocalProdCliente.setText(""+produt.getLocalizacao());
                jtfPotenciaProdCliente.setText(""+produt.getPotencia());
                recebeCamposProdCliente();
                produtoCliente = new ProdutoCliente(idProdCliente, idCliente, marca, potencia, voltagem, modelo, local);
            }

            System.out.println(proc);

            btnExcluir.setEnabled(true);
            btnCadastrar.setEnabled(true);
            //btnCadastrar.setEnabled(false);
        }
    }//GEN-LAST:event_jtProdCliMouseClicked

    private void jtfCodProdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodProdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodProdClienteActionPerformed

    private void jtfCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodClienteActionPerformed

    private void jtfMarcaProdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMarcaProdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMarcaProdClienteActionPerformed

    private void jtfModeloProdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfModeloProdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfModeloProdClienteActionPerformed

    private void jbtnSalvarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalvarProdActionPerformed
        if( !jtfMarcaProdCliente.getText().equals("") ||/* se os campos não estiverem vazios*/
            !jtfModeloProdCliente.getText().equals("") ||
            !jtfVoltagemProdCliente.getText().equals(""))
        {
            recebeCamposProdCliente();
            ProdutoCliente prod = new ProdutoCliente(idProdCliente, idCliente, marca, potencia, voltagem, modelo, local);
            if(idProdCliente>0)/*Se o codigo ja existir altera*/
            {
                switch (JOptionPane.showConfirmDialog(null, "Deseja realmente alterar as informações?","Atenção", JOptionPane.YES_NO_OPTION )) {
                    case 0:/*Botão 'Sim' clicado*/
                    ProdutoClienteController.modificar(prod);
                    break;
                    case 1:
                    break;
                }
            }    else{/*Se codigo não existir insert*/
                switch (JOptionPane.showConfirmDialog(null, "Deseja salvar as informações?","Atenção", JOptionPane.YES_NO_OPTION )) {
                    case 0:/*Botão 'Sim' clicado*/
                    ProdutoClienteController.cadastrar(prod);
                    break;
                    case 1:
                    break;
                }
            }
            buscaProdutos(idCliente);
        }else/*caso campos não estejam preenchidos*/
        JOptionPane.showMessageDialog(null, "Preencha as informações!");

    }//GEN-LAST:event_jbtnSalvarProdActionPerformed

    private void jbListarProdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListarProdClienteActionPerformed
        int busca = Integer.parseInt(jtfCodCliente.getText());
        buscaProdutos(busca);
    }//GEN-LAST:event_jbListarProdClienteActionPerformed

    private void jbAbrirOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAbrirOSActionPerformed
   criaJanelaJIIFOrdemServico();
        
    }//GEN-LAST:event_jbAbrirOSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apagar;
    private javax.swing.JButton Limpar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelaCadastro;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFbairro;
    private javax.swing.JButton jbAbrirOS;
    private javax.swing.JButton jbListarProdCliente;
    private javax.swing.JButton jbtnSalvarProd;
    private javax.swing.JComboBox<String> jcbPessoa;
    private javax.swing.JTextField jftNumero;
    private javax.swing.JTextField jftfCelular;
    private javax.swing.JTextField jftfCelular2;
    private javax.swing.JFormattedTextField jftfCep;
    private javax.swing.JFormattedTextField jftfTelefone;
    private javax.swing.JLabel jlNomeCliente;
    private javax.swing.JTable jtProdCli;
    private javax.swing.JTextField jtfCodCliente;
    private javax.swing.JTextField jtfCodProdCliente;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfLocalProdCliente;
    private javax.swing.JTextField jtfMarcaProdCliente;
    private javax.swing.JTextField jtfModeloProdCliente;
    private javax.swing.JTextField jtfPotenciaProdCliente;
    private javax.swing.JTextField jtfVoltagemProdCliente;
    private javax.swing.JTabbedPane jtpProdutos;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lblNomeFantasia;
    private javax.swing.JTable tabela;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JFormattedTextField txtIdPessoa;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtPessoa;
    // End of variables declaration//GEN-END:variables

   
    private String b="";
    /*Variáveis Cliente*/
    int codigo;
    String pessoa;
    String endereco;
    String cpf;
    String telefone;
    String celular;
    String celular2;
    String cep;
    String bairro;
    String email;
    String fantasia;
    String numero;
    
    /*Variáveis ProdCliente*/
    int idProdCliente;
    int idCliente = 0;
    String marca;
    String modelo;
    String local;
    String potencia;
    String voltagem;
    ProdutoCliente produtoCliente;
    
    
        public void recebeCamposPessoa(){
            if (txtIdPessoa.getText().length()>0){
                codigo   =  Integer.parseInt(txtIdPessoa.getText());
            }else codigo = 0;
        pessoa   =  txtPessoa.getText();
        endereco =  txtEndereco.getText();
        cpf      =  txtCPF.getText();
        telefone =  jftfTelefone.getText();
        celular  =  jftfCelular.getText();
        celular2 =  jftfCelular2.getText();
        cep      =  jftfCep.getText();
        email    =  jtfEmail.getText();
        bairro   =  jTFbairro.getText();
        numero   =  jftNumero.getText();
    }
        
        public void recebeCamposProdCliente(){
            if (txtIdPessoa.getText().length()>0){/*Enquanto não tiver cadastro de cliente selecionado nao recebe campos do produto*/
                codigo        =  Integer.parseInt(txtIdPessoa.getText());
                marca         =  jtfMarcaProdCliente.getText();
                modelo        =  jtfModeloProdCliente.getText();
                voltagem      =  jtfVoltagemProdCliente.getText();
                local         =  jtfLocalProdCliente.getText();
                potencia      =  jtfPotenciaProdCliente.getText();
            }else codigo = 0;
            
            if (jtfCodProdCliente.getText().length()>0){
                idProdCliente   =  Integer.parseInt(jtfCodProdCliente.getText());
            }else idProdCliente = 0;
        
    }
    
    public void preencheCampos(int pC){
       // List<Pessoa> pessoas = PessoaController.pesquisar(codigo);
        for (Pessoa ps : PessoaController.pesquisar(pC)){
            txtIdPessoa.setText(""+ps.getIdpessoa());
            txtPessoa.setText(ps.getNome());
            txtEndereco.setText(ps.getEndereco());
            txtCPF.setText(ps.getCpf());
            jftfTelefone.setText(ps.getTelefone());
            jftfCelular.setText(ps.getCelular());
            jftfCelular2.setText(ps.getCelular2());
            jftfCep.setText(ps.getCep());
            jtfEmail.setText(ps.getEmail());
            jTFbairro.setText(ps.getBairro());
            jftNumero.setText(ps.getNumero());
            
            jtfCodCliente.setText(""+ps.getIdpessoa());
            jlNomeCliente.setText(ps.getNome());
            idCliente = Integer.parseInt(jtfCodCliente.getText());
            buscaProdutos(idCliente);
        }
        
    }
    
//    public void preencheProdCliente(int pdC){
//        
//    }
    
    public void limpaCamposProdCliente(){
            jtfCodProdCliente.setText("");
            jtfMarcaProdCliente.setText("");
            jtfModeloProdCliente.setText("");
            jtfVoltagemProdCliente.setText("");
            jtfLocalProdCliente.setText("");
            jtfPotenciaProdCliente.setText("");
    }
       
    private void buscaInicial(String b){        
        
           MyTableModel busctab = new MyTableModel();
           String[] nomesColunas = new String[]{"ID","NOME", "CPF/CNPJ", "ENDEREÇO"};
           busctab.setColumnIdentifiers(nomesColunas);
           busctab.setNumRows(0);

            for (Pessoa p : PessoaController.pesquisar(b)) {
                            busctab.addRow(new Object[]{
                                p.getIdpessoa(),
                                p.getNome(),
                                p.getCpf(),
                                p.getEndereco()});
            }
            tabela.setModel(busctab);
            tabela.getColumnModel().getColumn(0).setPreferredWidth(5);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabela.getColumnModel().getColumn(2).setPreferredWidth(100);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(150);
            new Utilitarios().limparTodosCampos(rootPane);
    }             

     private MaskFormatter Mascara(String Mascara) {

        try {
            MaskFormatter stringMascara = new MaskFormatter(Mascara);
            //   stringMascara.setMask(Mascara);
            stringMascara.setPlaceholderCharacter(' ');
        } catch (Exception e) {            
            e.printStackTrace();
        }
            MaskFormatter stringMascara = null;
        return stringMascara;
     }

        public void inicia(){
        jcbPessoa.addActionListener(new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent event) {
            JComboBox<String> combo = (JComboBox<String>) event.getSource();
            String selectedBook = (String) combo.getSelectedItem();

            if (selectedBook.equals("PF")) {
                try {
                    System.out.println("Pessoa Fisica!");
                    txtCPF.setFormatterFactory(null);
                    javax.swing.text.MaskFormatter format = new javax.swing.text.MaskFormatter("###.###.###-##");
                    format.setPlaceholderCharacter('_');
                    txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(format));
                    txtCPF.setValue(null);
                    lblNomeFantasia.setEnabled(false);
                    txtNomeFantasia.setEnabled(false);
                } catch (ParseException ex) {
                    Logger.getLogger(JIFCadClientes.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else if (selectedBook.equals("PJ")) {
                try {
                    txtCPF.setFormatterFactory(null);
                    javax.swing.text.MaskFormatter format = new javax.swing.text.MaskFormatter("##.###.###/####-##");
                    format.setPlaceholderCharacter('_');
                    txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(format));
                    txtCPF.setValue(null);
                    lblNomeFantasia.setEnabled(true);
                    txtNomeFantasia.setEnabled(true);
                } catch (ParseException ex) {
                    Logger.getLogger(JIFCadClientes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    });
    }

    void setProduto(ProdutoCliente prod) {
        this.produto = prod;
    }

    private void buscaProdutos(int busca) {
        
           MyTableModel busctabe = new MyTableModel();
           
           String[] nomesColunas = new String[]{"ID","MARCA", "MODELO", "POTENCIA", "VOLTAGE","LOCALIZAÇÃO"};
           busctabe.setColumnIdentifiers(nomesColunas);
           busctabe.setNumRows(0);
           
           
           

            for (ProdutoCliente prodCliente : ProdutoClienteController.pesquisar(busca)) {
                            busctabe.addRow(new Object[]{
                                prodCliente.getIdProdCliente(),
                                prodCliente.getMarca(),
                                prodCliente.getModelo(),
                                prodCliente.getPotencia(),
                                prodCliente.getVoltagem(),
                                prodCliente.getLocalizacao()});
            }
            jtProdCli.setModel(busctabe);
            
            jtProdCli.getColumnModel().getColumn(0).setPreferredWidth(5);
            jtProdCli.getColumnModel().getColumn(1).setPreferredWidth(20);
            jtProdCli.getColumnModel().getColumn(2).setPreferredWidth(20);
            jtProdCli.getColumnModel().getColumn(3).setPreferredWidth(25);
            jtProdCli.getColumnModel().getColumn(4).setPreferredWidth(30);
            jtProdCli.getColumnModel().getColumn(5).setPreferredWidth(30);
            
            limpaCamposProdCliente();
            
            
    }

    
     private void criaJanelaJIIFOrdemServico() {
        JIIFOrdemServico jifOrdemServico = null;
        //se não foi instanciado ou se foi fechado, cria um novo
        if (jifOrdemServico == null || jifOrdemServico.isClosed()){
            
        jifOrdemServico  = new JIIFOrdemServico(produtoCliente, jdesk);
        jdesk.add(jifOrdemServico);
        jifOrdemServico.setClosable(true);
        jifOrdemServico.setVisible(true);
        //jifOrdemServico.setPosicao();
        }//senão envia a janela aberta pra frente
            else
            {
        jifOrdemServico.toFront();
        jifOrdemServico.grabFocus();
        }
    }
}

