/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisgelar.view.internal;

import javax.swing.table.DefaultTableModel;
import sisgelar.controller.OrdemServicoController;
import sisgelar.model.OrdemServico;
import sisgelar.model.ProdutoCliente;

/**
 *
 * @author kaike
 */
public class JIIFOrdemServico extends javax.swing.JInternalFrame {

    private ProdutoCliente prod;

    /**
     * Creates new form JIIFOrdemServico
     */
    public JIIFOrdemServico() {
        initComponents();
    }
    
    public JIIFOrdemServico(ProdutoCliente prod){
     this.prod = prod;   
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtOrdemServico = new javax.swing.JTable();

        jtOrdemServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Data/Hora", "Cliente", "Técnico"
            }
        ));
        jtOrdemServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtOrdemServicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtOrdemServico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtOrdemServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtOrdemServicoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtOrdemServicoMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtOrdemServico;
    // End of variables declaration//GEN-END:variables


      private void buscaInicial(String b){        
        
           DefaultTableModel busctab = new DefaultTableModel();
           String[] nomesColunas = new String[]{"ID","CLIENTE", "PRODUTO", "DESCRIÇÃO", "HORÁRIO"};
           busctab.setColumnIdentifiers(nomesColunas);
           busctab.setNumRows(0);

            for (OrdemServico p : OrdemServicoController.pesquisar(b)) {
                            busctab.addRow(new Object[]{
                                p.getIdOS(),
                                p.getIdCliente(),
                                p.getIdProdCliente(),
                                p.getDescricao(),
                                p.getHorario()
                                
                            });
            }
            jtOrdemServico.setModel(busctab);
            jtOrdemServico.getColumnModel().getColumn(0).setPreferredWidth(5);
            jtOrdemServico.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtOrdemServico.getColumnModel().getColumn(2).setPreferredWidth(100);
            jtOrdemServico.getColumnModel().getColumn(3).setPreferredWidth(150);
            //new Utilitarios().limparTodosCampos(rootPane);
    }           

}
